### ISSUE TITLE
I am getting the following errors when I try to run the code with python2 and 3 with tensorflow 0.12.1 installed along with essentia

### ISSUE THREAD

**Issue by shyamalschandra** [chrisdonahue/ddc#5]
I am getting the following errors when I try to run the code with python2 and 3 with tensorflow 0.12.1 installed along with essentia and other required packages.  Should I fix the bug myself or do you know if something is either wrong with my configuration or your configuration?

```
Shyamals-iMac:infer testuser$ python2 ./ddc_server.py
Traceback (most recent call last):
  File "./ddc_server.py", line 296, in <module>
    if not os.path.isdir(args.out_dir):
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
Shyamals-iMac:infer testuser$ python3 ./ddc_server.py
  File "./ddc_server.py", line 139
    print 'Extracting metadata from {}'.format(audio_fp)
                                      ^
SyntaxError: invalid syntax
```

**Comment by chrisdonahue** [comment]
It looks like you did not specify an output directory with "--out_dir"
